### ISSUE TITLE
Example for spring boot is build failed and run failed

### ISSUE THREAD

**Issue by sherryChen7** [saltedge/sca-identity-service-example#22]
**Summary:**  
Dear Dev team, I'm glad that you refactor the spring boot example, but unfortunately, the new version of example is build failed, please take a look, thank you.

**Steps to reproduce:**  
Follow the startup guild and try build the spring boot example.
Then, I face some issues:
1. Build failed issue
```
sca-identity-service-example/saltedge-sca-service-spring/example/src/main/kotlin/com/saltedge/sca/example/services/PaymentsService.kt: (91, 77): 
Too many arguments for public open fun createAction(@NotEmpty actionCode: @NotEmpty String!, uuid: String!, actionExpiresAt: LocalDateTime!): 
AuthenticateAction! defined in com.saltedge.sca.sdk.services.ScaSdkService
```
And I try to fixed it by myself:
```kt
    private fun createAuthenticateAction(): AuthenticateAction? {
//        return scaSdkService.createAction(
//                SCA_ACTION_LOGIN,
//                UUID.randomUUID().toString(),
//                null,
//                "Access to Spring Example Dashboard",
//                "Please confirm your that you authorize access to Spring Example Dashboard"
        return scaSdkService.createAction(
                SCA_ACTION_LOGIN,
                UUID.randomUUID().toString(),
                null
        );
    }
```

AND

```kt
    private fun createNewPaymentOrder(): PaymentOrder {
        val amount = (0 until 200).random().toDouble()
        val payment = PaymentOrder().apply {
            this.uuid = UUID.randomUUID().toString()
            this.amount = "%.2f".format(amount)
            this.currency = "EUR"
            this.payeeName = "Salt Edge Inc."
            this.payeeAddress = "40 King Street West, Suite 2100, Toronto, Ontario M5H3C2, Canada"
        }
        paymentsRepository.save(payment)
//        scaSdkService.createAction(SCA_ACTION_PAYMENT, payment.uuid, null,  null, null)
        scaSdkService.createAction(SCA_ACTION_PAYMENT, payment.uuid, null)
        return payment
    }
```

Then it's fixed, but I face another issue soon:
2. Run failed issue
```
Exception in thread "main" java.lang.NoSuchMethodException: com.saltedge.sca.example.ScaExampleApplication.main([Ljava.lang.String;)
	at java.lang.Class.getDeclaredMethod(Class.java:2130)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:47)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
```
And I try to fixed it by myself:
```kt
//open class ScaExampleApplication
//
//fun main(args: Array<String>) {
//    runApplication<ScaExampleApplication>(*args)
//}
open class ScaExampleApplication {
    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            runApplication<ScaExampleApplication>(*args)
        }
    }
}
```

Then it's fixed, but I face another issue soon:
3. Run failed issue 2
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-03-03 10:56:05 - o.s.boot.SpringApplication - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'scaController': Unsatisfied dependency expressed through field 'scaSdkService'; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'scaSdkService': Bean with name 'scaSdkService' has been injected into other beans [paymentsService] in its raw version as part of a circular reference, but has eventually been wrapped. This means that said other beans do not use the final version of the bean. This is often the result of over-eager type matching - consider using 'getBeanNamesOfType' with the 'allowEagerInit' flag turned off, for example.
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:643)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:116)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1422)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.saltedge.sca.example.ScaExampleApplication$Companion.main(ScaExampleApplication.kt:42)
	at com.saltedge.sca.example.ScaExampleApplication.main(ScaExampleApplication.kt)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)
Caused by: org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'scaSdkService': Bean with name 'scaSdkService' has been injected into other beans [paymentsService] in its raw version as part of a circular reference, but has eventually been wrapped. This means that said other beans do not use the final version of the bean. This is often the result of over-eager type matching - consider using 'getBeanNamesOfType' with the 'allowEagerInit' flag turned off, for example.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:624)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1287)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1207)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
	... 28 common frames omitted
```

I stuck in here, don't know how to fix it.

**Actual behavior:**  
`Tell us what happens instead`
Build failed and run failed.

**Expected behavior:**  
Build success and run success.

**Details**  
------------------------------------------------------------
Gradle 5.1.1
------------------------------------------------------------

Build time:   2019-01-10 23:05:02 UTC
Revision:     3c9abb645fb83932c44e8610642393ad62116807

Kotlin DSL:   1.1.1
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Mac OS X 10.15.3 x86_64

**Comment by ConstantinKV** [comment]
@sherryChen7 Thank you for your contribution. 
We have fixed the example app. Please pull changes and try to run the application. 
```
./gradlew bootRun
```

**Comment by sherryChen7** [comment]
@ConstantinKV 
I pull the changes and use `./gradlew bootRun`, it works now. Thank u.

But the older method is not work anymore.
The older method as below:
1. gradle build
2. Find xxx.jar under the build folder
3. java -jar xxx.jar

This make a little inconvenient when I want to build codes on my pc and deploy it on VPS(like GCP).
But I think it is okay,  not a big problem.
